### ISSUE TITLE
wrong statement in the training materials: pSched CLI

### ISSUE THREAD

**Issue by igarny** [perfsonar/training#5]
https://drive.google.com/file/d/0B1NNE6pjMJeAUGROd3JtckFrRWs/view
slide 20: --randslip

This is a non-existent switch. It should be --sliprand

Verified on Slack: https://perfsonar.slack.com/archives/C046RTY8K/p1510763551000452

**Comment by szymontrocha** [comment]
Corrected. v3 of the file uploaded to the Web.
